// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCategory(arg1) {
  return window['go']['main']['App']['AddCategory'](arg1);
}

export function AddGame(arg1) {
  return window['go']['main']['App']['AddGame'](arg1);
}

export function AddTag(arg1) {
  return window['go']['main']['App']['AddTag'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteGame(arg1) {
  return window['go']['main']['App']['DeleteGame'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetGameDetail(arg1) {
  return window['go']['main']['App']['GetGameDetail'](arg1);
}

export function ListCategories() {
  return window['go']['main']['App']['ListCategories']();
}

export function ListGames() {
  return window['go']['main']['App']['ListGames']();
}

export function ListTags() {
  return window['go']['main']['App']['ListTags']();
}

export function UpdateCategory(arg1) {
  return window['go']['main']['App']['UpdateCategory'](arg1);
}

export function UpdateGame(arg1) {
  return window['go']['main']['App']['UpdateGame'](arg1);
}

export function UpdateTag(arg1) {
  return window['go']['main']['App']['UpdateTag'](arg1);
}
