// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';
import {main} from '../models';

export function AddCategory(arg1:models.Category):Promise<models.Category>;

export function AddGame(arg1:models.Game):Promise<models.Game>;

export function AddGameDirectory(arg1:string):Promise<void>;

export function AddTag(arg1:models.Tag):Promise<models.Tag>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteGame(arg1:number):Promise<void>;

export function DeleteReport(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function ExportReportMarkdown(arg1:number):Promise<string>;

export function GenerateAIReport(arg1:services.AIReportRequest):Promise<models.Report>;

export function GetAISettings():Promise<services.AIConfig>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetDashboardStats():Promise<services.StatsOverview>;

export function GetGameDetail(arg1:number):Promise<services.GameDetail>;

export function GetGameDirectory():Promise<string>;

export function GetMonitorStatus():Promise<services.MonitorStatus>;

export function GetReport(arg1:number):Promise<models.Report>;

export function GetStatsByPeriod(arg1:string,arg2:string,arg3:string):Promise<services.StatsResult>;

export function ImportReportFromFile():Promise<models.Report>;

export function ImportScannedGames(arg1:Array<models.ScannedGame>):Promise<services.ImportResult>;

export function ListCategories():Promise<Array<models.Category>>;

export function ListGames():Promise<Array<models.Game>>;

export function ListReports():Promise<Array<models.Report>>;

export function ListTags():Promise<Array<models.Tag>>;

export function SaveAISettings(arg1:services.AIConfig):Promise<void>;

export function SaveImage(arg1:string,arg2:string):Promise<string>;

export function SaveReport(arg1:models.Report):Promise<models.Report>;

export function ScanGamesInDirectory(arg1:string,arg2:number):Promise<Array<models.ScannedGame>>;

export function SelectGameDirectory():Promise<string>;

export function StartMonitor():Promise<void>;

export function StopMonitor():Promise<void>;

export function TestAIConnection():Promise<void>;

export function UpdateCategory(arg1:models.Category):Promise<models.Category>;

export function UpdateGame(arg1:models.Game):Promise<models.Game>;

export function UpdateTag(arg1:models.Tag):Promise<models.Tag>;
