// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';
import {services} from '../models';

export function AddCategory(arg1:models.Category):Promise<models.Category>;

export function AddGame(arg1:models.Game):Promise<models.Game>;

export function AddTag(arg1:models.Tag):Promise<models.Tag>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteGame(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetGameDetail(arg1:number):Promise<services.GameDetail>;

export function ListCategories():Promise<Array<models.Category>>;

export function ListGames():Promise<Array<models.Game>>;

export function ListTags():Promise<Array<models.Tag>>;

export function UpdateCategory(arg1:models.Category):Promise<models.Category>;

export function UpdateGame(arg1:models.Game):Promise<models.Game>;

export function UpdateTag(arg1:models.Tag):Promise<models.Tag>;
