// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';
import {main} from '../models';

export function AddCategory(arg1:models.Category):Promise<models.Category>;

export function AddGame(arg1:models.Game):Promise<models.Game>;

export function AddGameDirectory(arg1:string):Promise<void>;

export function AddSaveArchive(arg1:number,arg2:string,arg3:string,arg4:boolean,arg5:string,arg6:string):Promise<models.SaveArchive>;

export function AddTag(arg1:models.Tag):Promise<models.Tag>;

export function BackupSaveArchive(arg1:number,arg2:string,arg3:string):Promise<models.SaveBackup>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteGame(arg1:number):Promise<void>;

export function DeleteReport(arg1:number):Promise<void>;

export function DeleteSaveArchive(arg1:number,arg2:boolean):Promise<void>;

export function DeleteSaveBackup(arg1:number,arg2:boolean):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function ExportReportMarkdown(arg1:number):Promise<string>;

export function GenerateAIReport(arg1:services.AIReportRequest):Promise<models.Report>;

export function GetAISettings():Promise<services.AIConfig>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetDashboardStats():Promise<services.StatsOverview>;

export function GetGameDetail(arg1:number):Promise<services.GameDetail>;

export function GetGameDirectory():Promise<string>;

export function GetMonitorStatus():Promise<services.MonitorStatus>;

export function GetReport(arg1:number):Promise<models.Report>;

export function GetStatsByPeriod(arg1:string,arg2:string,arg3:string):Promise<services.StatsResult>;

export function GetSteamSettings():Promise<services.SteamConfig>;

export function GetSteamSyncStatus():Promise<services.SteamSyncStatus>;

export function ImportReportFromFile():Promise<models.Report>;

export function ImportScannedGames(arg1:Array<models.ScannedGame>):Promise<services.ImportResult>;

export function ListCategories():Promise<Array<models.Category>>;

export function ListGames():Promise<Array<models.Game>>;

export function ListReports():Promise<Array<models.Report>>;

export function ListSaveArchives(arg1:number):Promise<Array<models.SaveArchive>>;

export function ListSaveBackups(arg1:number):Promise<Array<models.SaveBackup>>;

export function ListTags():Promise<Array<models.Tag>>;

export function SaveAISettings(arg1:services.AIConfig):Promise<void>;

export function SaveImage(arg1:string,arg2:string):Promise<string>;

export function SaveReport(arg1:models.Report):Promise<models.Report>;

export function SaveSteamSettings(arg1:services.SteamConfig):Promise<void>;

export function ScanGamesInDirectory(arg1:string,arg2:number):Promise<Array<models.ScannedGame>>;

export function SelectGameDirectory():Promise<string>;

export function SelectSaveArchiveDirectory():Promise<string>;

export function SelectSaveArchiveFile():Promise<string>;

export function SelectSaveBackupDirectory(arg1:string):Promise<string>;

export function StartMonitor():Promise<void>;

export function StopMonitor():Promise<void>;

export function SyncSteamLibrary():Promise<services.SteamSyncResult>;

export function TestAIConnection():Promise<void>;

export function UpdateCategory(arg1:models.Category):Promise<models.Category>;

export function UpdateGame(arg1:models.Game):Promise<models.Game>;

export function UpdateTag(arg1:models.Tag):Promise<models.Tag>;
