// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCategory(arg1) {
  return window['go']['main']['App']['AddCategory'](arg1);
}

export function AddGame(arg1) {
  return window['go']['main']['App']['AddGame'](arg1);
}

export function AddGameDirectory(arg1) {
  return window['go']['main']['App']['AddGameDirectory'](arg1);
}

export function AddSaveArchive(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddSaveArchive'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddTag(arg1) {
  return window['go']['main']['App']['AddTag'](arg1);
}

export function BackupSaveArchive(arg1, arg2, arg3) {
  return window['go']['main']['App']['BackupSaveArchive'](arg1, arg2, arg3);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteGame(arg1) {
  return window['go']['main']['App']['DeleteGame'](arg1);
}

export function DeleteReport(arg1) {
  return window['go']['main']['App']['DeleteReport'](arg1);
}

export function DeleteSaveArchive(arg1, arg2) {
  return window['go']['main']['App']['DeleteSaveArchive'](arg1, arg2);
}

export function DeleteSaveBackup(arg1, arg2) {
  return window['go']['main']['App']['DeleteSaveBackup'](arg1, arg2);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function ExportReportMarkdown(arg1) {
  return window['go']['main']['App']['ExportReportMarkdown'](arg1);
}

export function GenerateAIReport(arg1) {
  return window['go']['main']['App']['GenerateAIReport'](arg1);
}

export function GetAISettings() {
  return window['go']['main']['App']['GetAISettings']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetGameDetail(arg1) {
  return window['go']['main']['App']['GetGameDetail'](arg1);
}

export function GetGameDirectory() {
  return window['go']['main']['App']['GetGameDirectory']();
}

export function GetMonitorStatus() {
  return window['go']['main']['App']['GetMonitorStatus']();
}

export function GetReport(arg1) {
  return window['go']['main']['App']['GetReport'](arg1);
}

export function GetStatsByPeriod(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStatsByPeriod'](arg1, arg2, arg3);
}

export function ImportReportFromFile() {
  return window['go']['main']['App']['ImportReportFromFile']();
}

export function ImportScannedGames(arg1) {
  return window['go']['main']['App']['ImportScannedGames'](arg1);
}

export function ListCategories() {
  return window['go']['main']['App']['ListCategories']();
}

export function ListGames() {
  return window['go']['main']['App']['ListGames']();
}

export function ListReports() {
  return window['go']['main']['App']['ListReports']();
}

export function ListSaveArchives(arg1) {
  return window['go']['main']['App']['ListSaveArchives'](arg1);
}

export function ListSaveBackups(arg1) {
  return window['go']['main']['App']['ListSaveBackups'](arg1);
}

export function ListTags() {
  return window['go']['main']['App']['ListTags']();
}

export function SaveAISettings(arg1) {
  return window['go']['main']['App']['SaveAISettings'](arg1);
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2);
}

export function SaveReport(arg1) {
  return window['go']['main']['App']['SaveReport'](arg1);
}

export function ScanGamesInDirectory(arg1, arg2) {
  return window['go']['main']['App']['ScanGamesInDirectory'](arg1, arg2);
}

export function SelectGameDirectory() {
  return window['go']['main']['App']['SelectGameDirectory']();
}

export function SelectSaveArchiveDirectory() {
  return window['go']['main']['App']['SelectSaveArchiveDirectory']();
}

export function SelectSaveArchiveFile() {
  return window['go']['main']['App']['SelectSaveArchiveFile']();
}

export function SelectSaveBackupDirectory(arg1) {
  return window['go']['main']['App']['SelectSaveBackupDirectory'](arg1);
}

export function StartMonitor() {
  return window['go']['main']['App']['StartMonitor']();
}

export function StopMonitor() {
  return window['go']['main']['App']['StopMonitor']();
}

export function TestAIConnection() {
  return window['go']['main']['App']['TestAIConnection']();
}

export function UpdateCategory(arg1) {
  return window['go']['main']['App']['UpdateCategory'](arg1);
}

export function UpdateGame(arg1) {
  return window['go']['main']['App']['UpdateGame'](arg1);
}

export function UpdateTag(arg1) {
  return window['go']['main']['App']['UpdateTag'](arg1);
}
